### ISSUE TITLE
Please fix your commits

### ISSUE THREAD

**Issue by jcarrionramos** [tmunoz/DisastersClassification#3]
It is unacceptable that your commits be "asdjl ka dj". Please add useless changes in the files in that commit and document better.

It is really disgusting 👎 

cheers!

**Comment by tmunoz** [comment]
> It is unacceptable that your commits be "asdjl ka dj". Please add useless changes in the files in that commit and document better.
> 
> It is really disgusting 👎
> 
> cheers!

I'm sorry my colleague is learning to use GIT, but I will take your concerns to him and hopefully will improve.

Cheers !
